### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by AltarBeastiful** [FrancoisUPS/BioDecouverte#1]
- [x] Take Picture (Jonas)
- [ ] Geolocation (Jonas)
- [ ] Display picture
- [ ] Allow to choose a point on the picture and remember it 
- [ ] Start identification after picture activity (and pass the info of the picture to it?)
- [x] Display determination tree (Rémi)
- [ ] Choose a subnode in the determination tree (Rémi)
- [ ] Add a comment to the picture
- [ ] Access the pictures and metadata associated
- [ ] Send the picture and metadata to a specified mail address (could be hardcoded)
- [ ] Adapt Identification code to api v10 (Rémi)

**Comment by AltarBeastiful** [comment]
Une idée de comment passer les metadatas entre les différentes activités?

Dans les paramètres d'une activity on peut passer des String ou du serializable. Je l'utilise pour l'Identification (cf. Identification.java:onItemClick() ).

Une HashMap contenant les metadata et le chemin du fichier photo ?

**Comment by FrancoisUPS** [comment]
Vu que c'est déjà une Map autant les passer un par un non ?

```
intent.putExtra(k,v);
```

**Comment by AltarBeastiful** [comment]
Arf ouais mieux.

Bon j'arrive plus à lancer le projet, j'ai des erreurs de partout en essayant de passer le code à l'api 10 :/

**Comment by AltarBeastiful** [comment]
Go : https://trello.com/b/sknFI94k/bio
